### ISSUE TITLE
How to change user permissions on the project ?

### ISSUE THREAD

**Issue by MixMe** [loduis/teamwork.com-project-management#10]
I have user ID and Project ID, I want to give access to:
can_be_assigned_to_tasks_and_milestones
view_tasks_and_milestones
add_tasks

**Comment by send2dawood** [comment]
Kindly What is the difference between people instance and project/people instance even the code is same ?

2) I used the people instance with person_id it does not work, then I change the person_id with id then it worked

**Comment by loduis** [comment]
1. Project/People, main work is set the permission and is related to: http://developer.teamwork.com/permissions, Suddenly this is not the best name for this class

2. If users are already created, you must use Project/People: https://github.com/loduis/TeamWorkPmPhpApi/blob/master/src/Project/People.php#L144, if you are creating from scratch you can pass the parameter project_id in the People class: https://github.com/loduis/TeamWorkPmPhpApi/blob/master/src/People.php#L172

You hardly you should use Project / People, it's more like a helper, only for some specific occasions.
