### ISSUE TITLE
camelizeObject must be of type array, object given

### ISSUE THREAD

**Issue by alexscott64** [loduis/teamwork.com-project-management#42]
Hi, it appears that sometimes, teamwork will fail with the following error when inserting a task into a task list:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to TeamWorkPm\\Response\\JSON::camelizeObject() must be of the type array, object given, called in 
/site/vendor/myabakus/teamworkpm/src/Response/JSON.php on line 91 and defined in /site/vendor/myabakus/teamworkpm/src/Response/JSON.php:128

Stack trace:
#0 /site/vendor/myabakus/teamworkpm/src/Response/JSON.php(91): TeamWorkPm\\Response\\JSON::camelizeObject(Object(stdClass))
#1 /site/vendor/myabakus/teamworkpm/src/Rest.php(97): TeamWorkPm\\Response\\JSON->parse('{"STATUS":"OK",...', Array)
#2 /site/vendor/myabakus/teamworkpm/src/Rest.php(157): TeamWorkPm\\Rest->execute('GET', 'authenticate', NULL)
#3 /site/vendor/myabakus/teamworkpm/src/Account.php(38): TeamWorkPm\\Rest->get('authenticate')
#4 /site/vendor/myabakus/teamworkpm/src/Auth.php(18): TeamWorkPm\\Account->authenticate()
#5 /site/vendor/myabakus/teamworkpm/src/Response/JSON.php on line 128, referer: https://site.com/teamwork_request
```

I have a valid key that works, and like I said I usually have no issues adding to a task list. It just appears sometimes. Anyone have any idea on how to solve it?

**Comment by Biegalski-LLC** [comment]
I get this for every request now

**Comment by simonschaufi** [comment]
Could you share a test script so that I can also test it with my own account?

**Comment by oncallms** [comment]
For reference, I am able to replicate this error using the example script on the main repo page.
https://github.com/loduis/teamwork.com-project-management

**Comment by Biegalski-LLC** [comment]
For reference, I am able to replicate this error using the example script on the main repo page.
https://github.com/loduis/teamwork.com-project-management

**Comment by Biegalski-LLC** [comment]
Pull request made.

https://github.com/loduis/teamwork.com-project-management/pull/43

**Comment by simonschaufi** [comment]
thanx. merged.
