### ISSUE TITLE
Add "customFields" and "person" to "Project"

### ISSUE THREAD

**Issue by apsylone** [loduis/teamwork.com-project-management#52]
Hi,

I've tried to add "customFields" and "person" to "Project" model but I met a problem.
The attributes are arrays it seems the model doesn't accept it.
Could you help me implementing it ?

https://apidocs.teamwork.com/docs/teamwork/a0c29f3b330bd-create-project#request-body

**Comment by simonschaufi** [comment]
I'm on unable until August next year at least

**Comment by apsylone** [comment]
I think the library is really outdated and should implement newer version of the API.
I understand it requires a lot of time, but there is no alternatives at this time.

**Comment by nigel-wells** [comment]
@simonschaufi I was going to do some work on this repo as I need some additional functionality in it and would prefer to expand on what is here rather than create my own one. The unit tests appear to be referencing projects that don't exist - have they been removed now?

**Comment by loduis** [comment]
Add custom field support to project
![image](https://github.com/loduis/teamwork.com-project-management/assets/451862/8fa8699e-2740-4ded-a6a5-92479bdbeabd)

You can see the custom field in the project
![image](https://github.com/loduis/teamwork.com-project-management/assets/451862/ef9b07cb-55de-4b89-931c-00bec5fd4a9e)

**Comment by simonschaufi** [comment]
> have they been removed now?

yes. That is why I setup my own test instance on teamwork.com but I won't share that with the community. The tests should actually not really be executed but work with a fake API that returns given responses.
