### ISSUE TITLE
Adding Teamwork Desk TicketID When Creating a Task

### ISSUE THREAD

**Issue by joesken** [loduis/teamwork.com-project-management#53]
Hi,

We wrote small utility to automatically create tasks when a Teamwork Desk ticket is opened.  Thank you greatly for this library which helped along the way.

One thing we couldn't do by default was send in the Desk Ticket ID when creating the task.

We added this in in `Task.php` as follows L57:

```
            'ticketId'=>[
                'required'=>false,
                'attributes'=>[
                    'type'=>'integer'
                ]
            ],
```

Happy to create a PR on this if you think it is useful (and you are accepting PRs). Thanks again.

Joseph

**Comment by simonschaufi** [comment]
Hi Joseph, sure, if this is officially documented and supported we will gladly accept a PR from you.

**Comment by joesken** [comment]
Thanks @simonschaufi - PR attached, any questions just let me know.
