### ISSUE TITLE
Deprecated return types PHP 8+

### ISSUE THREAD

**Issue by zachauker** [loduis/teamwork.com-project-management#57]
Receiving PHP warnings related to return type compatibility issues introduced with recent versions of PHP that enforce stricter compliance with the built-in interface method signatures (IteratorAggregate, Countable, ArrayAccess, etc.). 

Return Type Issues: PHP 8+ introduces stricter return type checking for methods that implement certain built-in interfaces, such as IteratorAggregate, Countable, and ArrayAccess. The TeamWorkPm\Response\Model class methods do not have the correct return types defined as per these interfaces. The warnings specify that in order to make these methods compatible, adding the appropriate return types or by using a #[\ReturnTypeWillChange] attribute as a temporary solution.

## Examples

```DEPRECATED  Return type of TeamWorkPm\Response\Model::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/myabakus/teamworkpm/src/Response/Model.php on line 52.```

``` DEPRECATED  Return type of TeamWorkPm\Response\Model::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in vendor/myabakus/teamworkpm/src/Response/Model.php on line 57.```

**Comment by simonschaufi** [comment]
fixed with https://github.com/loduis/teamwork.com-project-management/commit/7037fc425a8dc4ddba6e2667fb8f9998164bc8a4
